name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  iai:
    name: Bench (iai)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Valgrind
      run: sudo apt install valgrind # sudo is necessary!
    - name: Build
      run: cargo build --verbose
    - name: Bench
      run: cargo bench --verbose
